### ISSUE TITLE
WAN interface (ens3) gets configured

### ISSUE THREAD

**Issue by valtzu** [hetznercloud/hc-utils#4]
I'm trying to setup a private network where the CX11 instances are not directly reachable from the internet.

I have disabled network cloud config
**/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg**
```yaml
network:
  config: disabled
```

**/etc/netplan/50-cloud-init.yaml**
```yaml
      network:
        version: 2
        ethernets:
          ens10:
            dhcp4: true
            routes:
              - to: 0.0.0.0/0
                via: 10.0.0.1
```

This works kinda ok if I remove the **hc-utils** package, then I'll have ens10 (private, configured, up) and ens3 (public, unconfigured, down) interfaces. However, if I do not remove hc-utils package, then the WAN interface will get automatically configured and up on reboot and there seems to be no way to change that behavior.

As I understood, this package is mainly meant for private network configuration so that probably should not happen, right?

I think the issue is that when WAN configuration is removed, the device name will change from `eth0` to `ens3` and that will cause the device look like a private network device for this hc-utils package.

Anyway, thanks for developing open source tools. :+1:
